version: '3'

services:
  apache:
    image: 'php:7.4-apache'
    container_name: php
    restart: always
    ports:
    - '8080:80'
  volumes:
    - ./html:/var/www/projeto2/
depends_on:
- mysqldb
links:
- mysqldb

mysqldb:
    container_name: mysqlASW
    image: mysql:5.7
    restart: always
    ports:
    - '3307:3306'
environment:
- MYSQL_ROOT_PASSWORD=pindamonhangaba_ativa
- MYSQL_DATABASE=argus_studio